/* Exercise local explorer logic without claiming browser rendering. Adityavardhan Mishra. */
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
let drawCalls=0;const software=process.argv.includes('--software');let softwareFills=0;const gl=new Proxy({getShaderParameter:()=>true,getProgramParameter:()=>true,getAttribLocation:()=>0,createShader:()=>({}),createProgram:()=>({}),createBuffer:()=>({}),bufferData:(target,data)=>assert([...data].every(Number.isFinite)),drawArrays:()=>drawCalls++},{get:(o,k)=>k in o?o[k]:()=>{}});
const ctx=new Proxy({fill:()=>softwareFills++},{get:(o,k)=>k in o?o[k]:()=>{}});const nodes={};
for(const [id,value] of Object.entries({model:'lunar_carrier',azimuth:'35',staging:'1000',apsis:'perilune',speed:'2',payload:'',wire:'',reset:'',modelCanvas:'',orbitCanvas:'',orbitReadouts:''}))nodes[id]={value,checked:id==='payload',getContext:type=>type==='webgl'?(software?null:gl):ctx,addEventListener:()=>{},setPointerCapture:()=>{},after:()=>{}};
const context=vm.createContext({window:{},document:{getElementById:id=>nodes[id],createElement:()=>({})},console});
for(const file of ['assets/lunar/concept_meshes.js','assets/lunar/mission_data.js','lunar.js'])vm.runInContext(fs.readFileSync(path.join(root,'docs',file),'utf8'),context);
for(const model of Object.keys(context.window.VOLLEY_MODELS)){nodes.model.value=model;for(const wire of [true,false])for(const payload of [true,false]){nodes.wire.checked=wire;nodes.payload.checked=payload;vm.runInContext('drawModel()',context)}}
for(const c of context.window.VOLLEY_LUNAR.releases){nodes.staging.value=String(c.staging_apo_km);nodes.apsis.value=c.apsis;nodes.speed.value=String(c.u_ms);vm.runInContext('drawOrbit()',context);assert(nodes.orbitReadouts.innerHTML.includes(c.payload.peri_km.toFixed(2)+' km'));assert(nodes.orbitReadouts.innerHTML.includes(c.host_dv_ms.toFixed(4)+' m/s'));assert(!/NaN|undefined/.test(nodes.orbitReadouts.innerHTML))}
if(software)assert(softwareFills>100);
const out={software_renderer:software,software_fills:softwareFills,logic_checks:'PASS',models:5,orbit_cases:42,finite_vertex_buffer_checks:true,draw_calls:drawCalls,real_browser_rendering:'NOT_EXECUTED_BY_THIS_CHECK',limits:'Stubbed graphics and DOM verify data/control paths only. WebGL compilation, raster output, mobile layout and pointer behavior need actual browser verification.'};fs.writeFileSync(path.join(root,software?'validation/logs/lunar-ui-software-logic.json':'validation/logs/lunar-ui-logic.json'),JSON.stringify(out,null,2)+'\n');console.log(out);
