"""One-shot current-state text reconciliation. Delete after use."""
from pathlib import Path


def replace_n(path, old, new, expected=1):
    p = Path(path)
    text = p.read_text(encoding="utf-8")
    count = text.count(old)
    if count != expected:
        raise SystemExit(f"{path}: expected {expected} match(es), found {count}")
    p.write_text(text.replace(old, new), encoding="utf-8")


replace_n("tools/export_companion.py", "> The programme has since moved to Gen6, which keeps the same mission and changes the\n> integration: the stage's own structure and 8 m of length become part of the machine, and cold\n> gas replaces the electromagnetic drive. The manuscript has not moved with it, deliberately.\n> Gen5 is the fully analysed configuration and Gen6 has not yet reached the same standard, the\n> [computational-closure target](https://github.com/aaaaaaaaaaaavm/VOLLEY/blob/main/docs/COMPUTATIONAL_CLOSURE.md)\n> is what it has to clear first. *A paper does not follow a design target; it follows evidence.*", "> The programme has since moved beyond Gen5, but the manuscript has not moved with it,\n> deliberately. The current calculation reference is a clean-sheet compact architecture with\n> independent retained cells, a motor-charged mechanical accumulator, latch, short guided pusher\n> and local catcher. The earlier 8 m cold-gas machine remains a historical comparator. Neither\n> direction inherits Gen5's evidence. *A paper does not follow a design target; it follows evidence.*")

old_target = "On 2026-08-14 five\nanalyses in the main repository replaced the design target: Gen6 is the payload accelerated\ndirectly, by cold gas, along a rail a spent upper stage provides (ADR-032). No mover, no\npulse-power chain, no brake, no return stroke.\n\nNothing in Gen6 is measured, its fluid system is unsized, its cradle mechanism does not exist,\nand no launch provider has agreed to lend a stage, which is exactly why the manuscript still\ncarries Gen5. A paper reports what has been analysed to a declared standard, not what looks best\nthis week."
new_target = "The main repository first moved the design target to an approximately 8 m stage-integrated\ncold-gas machine in August 2026, then reopened the mechanism after mission work showed that the\nhighest available release speed did not improve the best tested two-payload campaign. The current\ncalculation reference is now a compact independent stored-energy release cell. The gas machine\nremains in the record as a historical comparator with its failures intact.\n\nNothing in the current reference is measured, its detailed accumulator, latch, guide, catcher and\nstructure are unselected, and no launch provider has supplied an accommodation. That is exactly\nwhy the manuscript still carries Gen5. A paper reports what has been analysed to a declared\nstandard, not what looks best this week."
replace_n("tools/export_companion.py", old_target, new_target, expected=2)

replace_n("tools/export_companion.py", '<img src="cad/renders/gen6/hero_open.png" alt="Gen6 stage-integrated gas architecture target" width="32%">', '<img src="cad/renders/gen6/hero_open.png" alt="Historical stage-integrated gas Gen6 study" width="32%">')
replace_n("tools/export_companion.py", "| Stage-integrated system, Gen6 | The stage's own structure and 8 m of length become part of the machine; cold gas replaces the drive. Same mission, far less duplicated hardware |", "| Historical stage-integrated gas Gen6 | The stage's own structure and about 8 m of length become part of the machine; retained as a comparator after guide/contact and trim/tube problems were exposed |\n| Clean-sheet Gen6 reference | Independent retained cells use slowly charged mechanical storage, an independent latch, short guided pusher and local catcher; selected for the next calculations, not as flight hardware |")

replace_n("tools/profile-readme/README.md", "In 2021 I got stuck on a dumb question: why do we still deploy CubeSats with springs. I never\nreally got unstuck. That question is now VOLLEY: an electromagnetic deployer that ejects\nunmodified 3U CubeSats at a programmable velocity from a spent rideshare upper stage. I've\npresented it at DRDO ARDE and the India Science Festival.", "In 2021 I got stuck on a dumb question: why do we still deploy CubeSats with springs. I never\nreally got unstuck. That question is now VOLLEY: a spacecraft-deployment programme investigating\nprovider-hosted control of individual payload departure conditions. Gen5 is the frozen\nelectromagnetic machine; the current clean-sheet reference is a compact independent stored-energy\nrelease cell. I've presented the project at DRDO ARDE and the India Science Festival.")

replace_n("tools/profile-readme/README.md", "[VOLLEY](https://github.com/aaaaaaaaaaaavm/VOLLEY), a magazine-fed ironless double-sided\nHalbach linear synchronous motor that ejects unmodified CubeSats at 16.029 m/s and 10.07 g,\ndrawing 2.78 kJ gross and 2.74 kJ net per shot. TRL 2-3. Nothing built, fired or measured.\n\nThe design target has since moved, and the reason is the best result in the project. I\nattributed every kilogram of the deployer to the requirement that causes it, then deleted every\nrequirement in all 64 combinations to find the lightest machine any relaxation could reach.\n88.67 kg survives all of them, 70 % of dry mass, against a 2 kg-per-satellite criterion. There\nis no version of Gen5 that meets its own mass target. So the target changed from shrinking\nsubsystems to deleting them: the payload accelerated directly, by cold gas, along a rail the spent\nstage already provides. The architecture that was the target the day before is kept in full,\nwith the analysis that retired it at the top of it.\n\nGen5 keeps every headline number, because Gen5 is what has the structural FEA, the CFD, the\ndesigned control loop and the second CAD implementation behind it. The current direction has none\nof those and does not inherit them. Both are published side by side rather than one quietly\nreplacing the other.", "[VOLLEY](https://github.com/aaaaaaaaaaaavm/VOLLEY) now treats the mechanism as the thing to\nprove, not the premise. Gen5 is the frozen magazine-fed ironless double-sided Halbach LSM:\n16.029 m/s, 10.07 g, 126.6 kg dry, modelled only. Its mass criterion failed and stays failed.\nNothing in the programme has been built, fired or measured.\n\nThe project then tried an approximately 8 m stage-integrated cold-gas architecture. That work\nexposed useful pressure, guide/contact and trim/tube evidence, but it is no longer the assumed\nanswer either. S4's bounded two-payload mission screen found that BOLLEY, Gen5 and the gas-Gen6\nauthority screens all reached the same best tested fuel result with a 4.569852 m/s first release.\nHigher available release speed bought nothing in that tested campaign.\n\nSo the current clean-sheet reference is deliberately smaller: independent retained cells, a\nmotor-charged mechanical accumulator, independent latch, short guided pusher and local catcher.\nAt the S4 study point a 4 kg payload carries 41.77 J of ideal kinetic energy and a 10 g\nconstant-acceleration screen is 106.5 mm. Those are study numbers, not a product requirement.\nThe next job is to try to kill that reference on uncertainty, installed burden, latch/pusher\nbehaviour, tip-off and catcher loads before detailed CAD.")

print("current-state text patches applied")
