"""Generate the IEEE and thesis companion repositories from the flagship.

WHY THIS EXISTS
---------------
`16.537 m/s` appears in nine places in the flagship. Four hand-maintained repositories would
make divergence a certainty, and this project has already produced two forks of exactly that
kind: the operating point between motor_model.py and sizing.py (now guarded by
_check_operating_point), and the paper figures against the analysis (now regenerated by
tools/make_figures.py). This is the same answer applied a third time.

The companions are OUTPUT. Nothing in them is authored. Every generated file carries a header
saying so and naming the flagship commit it came from. If a companion is ever hand-edited, the
correct response is to delete and regenerate it -- not to reconcile the two copies.

USAGE
    python3 tools/export_companion.py --out ../companions          # both
    python3 tools/export_companion.py --out ../companions --only paper

Then, in each generated directory:
    git init && git add -A && git commit && git remote add origin <url> && git push
or use tools/bootstrap_repos.sh, which does that for all of them.
"""
import argparse
import os
import shutil
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The shared cross-link block. Byte-identical in all four repositories -- the flagship's copy
# in PROGRAMME.md is the source, and this is checked by tools/check_links.py.
HEADER_ROWS = [
    ("VOLLEY", "Main: the authoritative engineering record. Improved continuously", ""),
    ("VOLLEY-paper", "The concept at its most reliable, as an IEEE-formatted manuscript. **Frozen when published**", "paper"),
    ("VOLLEY-thesis", "The same concept as a full submission. **Frozen when presented**", "thesis"),
    ("VOLLEY-lab", "The vault: ideas that never became a complete thing, and why each stopped", "lab"),
]
OWNER = "aaaaaaaaaaaavm"

# The generated directory name has to match the repository it is pushed to. Override it if the
# repositories have not been renamed yet:
#
#     REPO_PREFIX=EMOCD python3 tools/export_companion.py --out ../companions
#
# Getting this wrong does not fail loudly. `gh repo create` in bootstrap_repos.sh would simply
# create a second, empty repository under the other name and push to that, leaving the real one
# untouched and the mistake invisible until someone opens the wrong URL.
REPO_PREFIX = os.environ.get("REPO_PREFIX", "VOLLEY")
# The flagship repository these are generated from. Follows REPO_PREFIX so the
# provenance banner cannot point at a repository name that no longer exists.
FLAGSHIP = REPO_PREFIX


def header_table(here):
    """`here` is '', 'paper', 'thesis' or 'lab'."""
    out = ["<!-- PROGRAMME-HEADER-START -->",
           "| Repository | Role | You are here |", "|---|---|---|"]
    for name, role, key in HEADER_ROWS:
        link = f"[{name}](https://github.com/{OWNER}/{name})"
        cell = f"**{link}**" if key == here else link
        out.append(f"| {cell} | {role} | {'←' if key == here else ''} |")
    out.append("<!-- PROGRAMME-HEADER-END -->")
    return "\n".join(out)


AUTHORED = {
    "paper": ("the manuscript, its class file, the built PDF, the CV and the submission "
              "archive, all under `paper/`"),
    "thesis": ("the manuscript and its figures under `source/`, and everything under "
               "`university/`"),
}

FREEZE = {
    "paper": "published",
    "thesis": "presented",
}


def banner(commit, kind):
    """The provenance block at the top of a companion README.

    THIS USED TO SAY "nothing here is authored". That stopped being true on 2026-08-13,
    when ADR-028 moved the manuscript out of the engineering record and into the companions
    and ADR-031 gave the companions a role of their own. A banner that tells a contributor
    every file will be overwritten, in a repository where some files never are, is worse
    than no banner: it is wrong in the direction that loses work.
    """
    return f"""> ## What is generated here, and what is not
>
> **Generated** from [{OWNER}/{FLAGSHIP}](https://github.com/{OWNER}/{FLAGSHIP}) at commit
> `{commit}` by `tools/export_companion.py`: the analysis scripts and their results, the
> validation run sheets, the figures, and the reference records. Any edit to those is
> destroyed on the next export. **Fix them in {FLAGSHIP} and this repository picks the fix up.**
>
> **Authored here, and never overwritten:** {AUTHORED[kind]}. {FLAGSHIP} is an engineering
> record and holds no manuscript source.
>
> Where a generated file disagrees with {FLAGSHIP}, {FLAGSHIP} is right and this copy is stale.
>
> **This repository may be improved until the work is {FREEZE[kind]}, and freezes at that
> moment.** What enters it has to be stable, effective and reliable against the problem
> statement -- not merely newer.

{header_table(kind)}
"""


# path in flagship -> path in companion. Directories copied recursively.
# THE MANUSCRIPT IS NO LONGER EXPORTED. `paper.tex`, `IEEEtran.cls`, the built PDF, the CV
# and the archive are AUTHORED in VOLLEY-paper as of 2026-08-13 (ADR-028); the flagship is an
# engineering record and holds no LaTeX. What is still generated from here is the
# reproducibility payload -- the scripts, the run sheets and the figures behind every number.
PAPER_MANIFEST = [
    ("figures", "paper/figures"),
    ("tools/make_figures.py", "paper/make_figures.py"),
    ("tools/make_animation.py", "paper/make_animation.py"),
    ("analysis", "analysis"),
    ("requirements.txt", "requirements.txt"),
    ("validation", "validation"),
    ("docs/PROVENANCE.md", "PROVENANCE.md"),
    ("docs/PRIOR_ART.md", "PRIOR_ART.md"),
    ("docs/LITERATURE.md", "LITERATURE.md"),
    ("docs/BASELINE.md", "BASELINE.md"),
    # LICENCE HELD, 2026-08-10. The flagship is CC BY 4.0; this companion deliberately is
    # not, and ships the superseded MIT text as its LICENSE instead. Relicensing the IEEE
    # manuscript sets terms that an IEEE copyright transfer on acceptance would supersede,
    # and this repository cannot license rights it has transferred.
    #
    # The mapping below is the mechanism: source LICENSE-MIT-superseded, destination LICENSE.
    # It means a plain `export_companion.py` run CANNOT relicense this companion by accident.
    #
    # TO RELEASE THE HOLD once the manuscript's status is settled, replace the line below with
    #     ("LICENSE", "LICENSE"),
    #     ("NOTICE", "NOTICE"),
    #     ("LICENSING.md", "LICENSING.md"),
    #     ("LICENSE-MIT-superseded", "LICENSE-MIT-superseded"),
    #     ("CITATION.cff", "CITATION.cff"),
    # which is what THESIS_MANIFEST already carries.
    ("LICENSE-MIT-superseded", "LICENSE"),
]

THESIS_MANIFEST = [
    ("figures", "source/figures"),
    ("analysis", "analysis"),
    ("validation", "validation"),
    ("cad", "cad"),
    ("CAD_BRIEF.md", "appendix/CAD_BRIEF.md"),
    ("docs/GEN4_STATUS.md", "appendix/GEN4_STATUS.md"),
    ("docs/BASELINE.md", "appendix/BASELINE.md"),
    ("OPEN_PROBLEMS.md", "appendix/OPEN_PROBLEMS.md"),
    ("docs/VALIDATION_REPORT.md", "appendix/VALIDATION_REPORT.md"),
    ("docs/PROVENANCE.md", "appendix/PROVENANCE.md"),
    ("CHANGELOG.md", "appendix/CHANGELOG.md"),
    ("docs/HISTORY.md", "appendix/HISTORY.md"),
    ("docs/DECISION_LOG.md", "appendix/DECISION_LOG.md"),
    ("docs/adr", "appendix/adr"),
    ("docs/PRIOR_ART.md", "appendix/PRIOR_ART.md"),
    ("docs/LITERATURE.md", "appendix/LITERATURE.md"),
    ("docs/RELATED_WORK.md", "appendix/RELATED_WORK.md"),
    ("LICENSE", "LICENSE"),
    ("NOTICE", "NOTICE"),
    ("LICENSING.md", "LICENSING.md"),
    ("LICENSE-MIT-superseded", "LICENSE-MIT-superseded"),
    ("CITATION.cff", "CITATION.cff"),
]

PAPER_README = """# VOLLEY: the manuscript

**An IEEE-formatted technical manuscript, and everything needed to check it.**

Rideshare CubeSats inherit the orbit of whoever paid for the launch. This paper describes a
deployer that gives each of twelve satellites an orbit chosen for it, without modifying any of
them — and reports, in the same voice, the three thresholds the design currently fails.

**[Read the paper](paper/VOLLEY_IEEE_Conference.pdf)** — **18 pages, current build.**
Print-ready copies: **[A4](print/Adityavardhan_Mishra_VOLLEY_IEEE_2026_A4_Print.pdf)** ·
**[US Letter](print/Adityavardhan_Mishra_VOLLEY_IEEE_2026_Letter.pdf)**. Both come from one source
and are content-identical; only the page geometry differs.

> **It is IEEE-*formatted*, using the IEEEtran class. It is not claimed to be submission-compliant
> for any venue** — page and abstract limits are set by the conference or journal, and **no venue
> has been selected and nothing has been submitted.**

Every number in it comes from a script in this repository, and every analysis behind it declared
what would count as failure **before** it ran. Nothing has been built, fired or measured.

## Reproduce it in one command

```bash
pip install -r requirements.txt
cd analysis && python3 verify_field.py && python3 mass_properties.py \\
  && python3 motor_model.py && python3 sizing.py && python3 payload_family.py \\
  && python3 astro.py && python3 comparators.py && python3 cost.py
```

Roughly two minutes, and the order matters: everything downstream reads the rated shot from
`motor_results.json` rather than restating it. Results land in `analysis/results/*.json`.

This has been checked from a clean clone rather than assumed: run that way, `motor_results.json`
returns `shot.v_exit = 16.029`, which is the figure the paper's abstract quotes.

## What reproduces, and how well

| Quantity | Value | Cross-checked against |
|---|---|---|
| Thrust constant, depth-resolved | 10.54 N per kA/m | Nothing independent. The FEM check below is of the centre-plane value it derives from |
| Thrust constant, centre-plane | 11.03 N per kA/m | A meshed 2-D magnetostatic FEM, agreeing to 0.03 % |
| Airgap field | 0.694 T midgap peak | magpylib, agreeing to three digits |
| Orbital decay | x1.60 lifetime | Cowell RK4, agreeing to 99.4 % |
| Exit velocity | 16.029 m/s at 10.07 g | Single-sourced |
| Dispersion | 0.0274 m/s, 3 sigma | Single-sourced, and resting on assumed sensor noise |

Only two rows carry an independent check. `PROVENANCE.md` says which of these carry weight.

## Figures

`python3 paper/make_figures.py` regenerates all of them. It imports the analysis rather than
reimplementing it, so a figure cannot quietly disagree with the number it plots.

## Before citing

**Read [`PROVENANCE.md`](PROVENANCE.md).** This is a design study at TRL 2-3. Nothing has been
built, fired or measured, and the paper says so.

[`PRIOR_ART.md`](PRIOR_ART.md) records the published work nearest to this one, including two
claims the paper had to retract after reading it. [`LITERATURE.md`](LITERATURE.md) maps the wider
field.


## The manuscript describes Gen5, and the design target has moved

**This is deliberate and worth stating plainly.** Everything reproduced here is **Gen5** — the
analysed baseline -- a frozen computational one, with no hardware behind it -- and the record of
what a self-contained deployer costs. On 2026-08-14 five
analyses in the main repository replaced the design target: **Gen6 is the payload accelerated
directly, by cold gas, along a rail a spent upper stage provides** (ADR-032). No mover, no
pulse-power chain, no brake, no return stroke.

**Nothing in Gen6 is measured**, its fluid system is unsized, its cradle mechanism does not exist,
and no launch provider has agreed to lend a stage — which is exactly why the manuscript still
carries Gen5. A paper reports what has been analysed to a declared standard, not what looks best
this week.

**The main repository carries both**, and the failures at the same standard as the results.

## What is deliberately absent

The engineering record. Decision log, defect ledger, CAD generations, roadmap and change history
live in the flagship. This package exists so the paper can be checked, not so it can stand in for
the repository it came from.
"""

THESIS_README = """# VOLLEY: the thesis

**A final-year thesis on giving rideshare CubeSats an orbit their host was not going to — and
the full record of what went wrong on the way there.**

**[Read the manuscript](source/VOLLEY_IEEE_Conference.pdf)**

The submission is here with its analyses, its acceptance tests and its defect register attached.
The defects are deliberate: an examiner should be able to see what failed, when it was found, and
what was done about it. Nothing in it has been built or measured.

## Layout

| | |
|---|---|
| `source/` | Manuscript and figures |
| `analysis/` | The scripts producing every number in the work |
| `validation/` | The analyses, each with its acceptance bands declared before the run |
| `cad/` | The CAD generations, with the defect audit for each |
| `appendix/` | Baseline, defect ledger, validation report, provenance, prior art, literature, decision records |

## For an examiner, in reading order

1. `appendix/PROVENANCE.md`, which says what stands behind each claim and what does not.
2. `appendix/BASELINE.md`, the frozen values, and the rule for changing any of them.
3. `appendix/adr/`, the decision records. Each states the alternatives considered and the
   consequences accepted. ADR-003 carries its own amendment showing an argument it got wrong.
4. `appendix/OPEN_PROBLEMS.md`, every known defect, including the ones that damage the work's own
   claims — and the ones found by checking this work against itself rather than by anyone asking.
5. `appendix/PRIOR_ART.md`, the nearest published work, and the two claims retracted after reading
   it.

The decision records are the part most worth reading. They are where the reasoning lives, and
several of them record the alternative that was rejected and why.

## What is authored here

`source/` holds the manuscript, which is written in this repository — the main record is an
engineering record and carries no manuscript source. `university/` holds submission forms,
formatting mandates and viva material, which are university-specific and do not belong upstream.
**Neither is ever touched by the export. Everything else is regenerated and will be overwritten.**

This repository may be improved until the thesis is presented, and freezes at that moment. What
enters it has to be stable, effective and reliable against the problem statement.


## The manuscript describes Gen5, and the design target has moved

**This is deliberate and worth stating plainly.** Everything reproduced here is **Gen5** — the
analysed baseline -- a frozen computational one, with no hardware behind it -- and the record of
what a self-contained deployer costs. On 2026-08-14 five
analyses in the main repository replaced the design target: **Gen6 is the payload accelerated
directly, by cold gas, along a rail a spent upper stage provides** (ADR-032). No mover, no
pulse-power chain, no brake, no return stroke.

**Nothing in Gen6 is measured**, its fluid system is unsized, its cradle mechanism does not exist,
and no launch provider has agreed to lend a stage — which is exactly why the manuscript still
carries Gen5. A paper reports what has been analysed to a declared standard, not what looks best
this week.

**The main repository carries both**, and the failures at the same standard as the results.

## Before citing

Every number here is a model output. Nothing has been built or measured. The defect ledger is
published deliberately rather than tidied away, and it is the honest measure of how far the work
has actually got.
"""


def tracked():
    """Every path git tracks in the flagship, as a set of repo-relative paths.

    WHY THIS EXISTS (P39). copy() used to walk the WORKING TREE, so anything sitting in a
    copied directory went into the companion whether or not it was in the flagship at all.
    That is how twelve CalculiX build artifacts -- plate.inp, plate_clamped.frd and the rest,
    outputs of running A4 -- ended up published in VOLLEY-paper and VOLLEY-thesis under a
    banner reading "generated from VOLLEY flagship 45332a7". They are in no VOLLEY commit,
    and `git log --diff-filter=A` finds them in none.

    The consequence is worse than the stray files: the companion depended on what happened to
    be lying around when the export ran, so the same flagship commit produced different
    companions on a machine that had run the analyses and on a clean clone. A generated
    artifact that is not a function of its stated input is not generated, it is collected.
    """
    out = subprocess.run(["git", "ls-files", "-z"], cwd=ROOT,
                         capture_output=True, text=True, check=True).stdout
    return {p for p in out.split("\0") if p}


TRACKED = None          # populated in main(), so importing this module costs no subprocess
SKIPPED = []


def copy(src, dst):
    s, d = os.path.join(ROOT, src), os.path.join(dst)
    os.makedirs(os.path.dirname(d) or d, exist_ok=True)
    if os.path.isdir(s):
        def ignore(dirpath, names):
            drop = set(shutil.ignore_patterns('__pycache__', '*.pyc', 'output')(dirpath, names))
            rel_dir = os.path.relpath(dirpath, ROOT)
            for n in names:
                if n in drop:
                    continue
                full = os.path.join(dirpath, n)
                rel = os.path.normpath(os.path.join(rel_dir, n))
                if os.path.isdir(full):
                    # keep a directory if anything under it is tracked
                    if not any(t.startswith(rel.replace(os.sep, "/") + "/") for t in TRACKED):
                        drop.add(n)
                elif rel.replace(os.sep, "/") not in TRACKED:
                    drop.add(n)
                    SKIPPED.append(rel.replace(os.sep, "/"))
            return drop
        shutil.copytree(s, d, dirs_exist_ok=True, ignore=ignore)
    elif os.path.exists(s):
        if src not in TRACKED:
            print(f"    UNTRACKED (skipped): {src}")
            SKIPPED.append(src)
            return 0
        shutil.copy2(s, d)
    else:
        print(f"    MISSING (skipped): {src}")
        return 0
    return 1


def build(kind, manifest, readme, out_root, commit):
    dest = os.path.join(out_root, f"{REPO_PREFIX}-{kind}")
    # Regenerate the MANIFEST paths wholesale, never merge into a stale tree -- but leave
    # everything else alone. Since ADR-028 the companions also carry AUTHORED content that
    # this tool does not produce and must not destroy: VOLLEY-paper holds the manuscript,
    # the .cls, the built PDF, the CV and the archive. Wiping the destination, which is
    # what this did until 2026-08-13, would delete the paper.
    for _, rel in manifest:
        victim = os.path.join(dest, rel)
        if os.path.isdir(victim):
            shutil.rmtree(victim)
        elif os.path.exists(victim):
            os.remove(victim)
    os.makedirs(dest, exist_ok=True)
    n = sum(copy(src, os.path.join(dest, rel)) for src, rel in manifest)
    with open(os.path.join(dest, "README.md"), "w") as f:
        f.write(banner(commit, kind) + "\n---\n\n" + readme)
    with open(os.path.join(dest, ".gitignore"), "w") as f:
        f.write("__pycache__/\n*.pyc\n*.aux\n*.log\n*.out\npaper.pdf\n")
    if kind == "thesis":
        os.makedirs(os.path.join(dest, "university"), exist_ok=True)
        with open(os.path.join(dest, "university", "README.md"), "w") as f:
            f.write("# University-specific material\n\n"
                    "**This directory is never touched by `export_companion.py`.** Submission "
                    "forms, templates, formatting mandates and viva material go here.\n\n"
                    "Everything outside this directory is generated and will be overwritten "
                    "on the next export.\n")
    print(f"  VOLLEY-{kind}: {n} paths -> {dest}")
    return dest


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True, help="directory to write the companions into")
    ap.add_argument("--only", choices=["paper", "thesis"], help="build just one")
    args = ap.parse_args()

    dirty = subprocess.run(["git", "status", "--porcelain"], cwd=ROOT,
                           capture_output=True, text=True).stdout.strip()
    if dirty:
        print("WARNING: flagship working tree is dirty. The companions will record a commit "
              "that does not match what was copied. Commit first.\n", file=sys.stderr)
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], cwd=ROOT,
                            capture_output=True, text=True).stdout.strip()

    global TRACKED
    TRACKED = tracked()

    out_root = os.path.abspath(args.out)
    os.makedirs(out_root, exist_ok=True)
    print(f"generating companions from flagship {commit} into {out_root} "
          f"({len(TRACKED)} tracked paths)")
    if args.only in (None, "paper"):
        build("paper", PAPER_MANIFEST, PAPER_README, out_root, commit)
    if args.only in (None, "thesis"):
        build("thesis", THESIS_MANIFEST, THESIS_README, out_root, commit)
    if SKIPPED:
        print(f"\nskipped {len(SKIPPED)} untracked path(s) -- these are in the working tree "
              f"but in no flagship commit, so they may not be published under its banner:")
        for p in sorted(set(SKIPPED))[:20]:
            print(f"    {p}")
        if len(set(SKIPPED)) > 20:
            print(f"    ... and {len(set(SKIPPED)) - 20} more")
    print("done. These are output -- do not edit them; edit the flagship and re-run.")


if __name__ == "__main__":
    main()
